#!/bin/sh

cd /bin
for i in $(busybox --list)
do
  ln -f -s busybox $i
done

mount -t proc none /proc
mount -t sysfs none /sys
mount -t tmpfs -o size=10 tmpfs /tmp
mdev -s

/usr/bin/sysinfo
loadkmap < /etc/keymap
udhcpc -i eth0 -s /etc/udhcpc/sample.script
httpd -h /www/ &

exec /bin/sh

exit 0
